### ISSUE TITLE
Is www.3dprinting-r2c2.com) is still in business?

### ISSUE THREAD

**Issue by Telemetrika** [bitboxelectronics/R2C2_Firmware#17]
Gentleman:

Can you please let us know if this company (www.3dprinting-r2c2.com) is still in business? We sent a couple of emails 3 days ago asking if PayPal can be used to purchase their R2C2 Starter Kit. We live in the US and need to purchase in USD$.

I’m interested in this board kit, please let me know if this project is still alive and being supported.

Thanks

**Comment by nneves** [comment]
Yes, they are, and pretty active! Let me warn them about your issue!

**Comment by casainho** [comment]
Telemetrika, please send your e-mail to: jpinto@bitbox.pt and comercial@bitbox.pt. Thank you.

**Comment by casainho** [comment]
We got your e-mail. Thank you.
