### ISSUE TITLE
G4 "dwell" command seems to hang printer

### ISSUE THREAD

**Issue by bobc** [bitboxelectronics/R2C2_Firmware#2]
The G4 command seems to hang indefinitely.

e.g. G4 P4

should wait 4 seconds and continue but hangs.

**Comment by bobc** [comment]
Seems that millis_ticks needs to be volatile even though it is accessed via a function call... smart compiler.

**Comment by casainho** [comment]
Good work.

**Comment by bobc** [comment]
I believe this is now fixed and in latest release build.
